### ISSUE TITLE
파일이랑 클래스 이름에 오타가 있습니다.

### ISSUE THREAD

**Issue by dalong417** [ReactComponentKit/ReactComponentKit#4]
https://github.com/ReactComponentKit/ReactComponentKit/blob/0261526d00fa7d08305a2ba5b8e3a10601254bc4/ReactComponentKitApp/ReactComponentKit/TableView/UITableViewAdatper.swift#L11

**Comment by skyfe79** [comment]
@dalong417 다롱님 감사합니다 👍 👍 👍
